server:
  port: 10000
spring:
  application:
    name: k8s-demo-redis
  cloud:
    nacos:
      discovery:
        server-addr: nacos-headless.default.svc.cluster.local
#        ip: k8s-demo-redis.svc.cluster.local
  redis:
    database: 0
    host: redis.dev.svc.cluster.local
    port: 6379
    Password: dream123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000