apiVersion: v1
kind: Pod
metadata:
  name: pod-initcontainer
  namespace: dev
spec:
  containers:
  - name: main-container
    image: nginx:1.17.1
    ports:
    - name: nginx-port
      containerPort: 80
  initContainers:
  - name: test-mysql
    image: busybox:1.30
    command: ["sh", "-c", "until ping 192.168.80.201 -c 1 ; do echo wating for mysql...; sleep2; done;"]
  - name: test-redis
    image: busybox:1.30
    command: ["sh", "-c", "until ping 192.168.80.202 -c 1 ; do echo wating for redis...; sleep2; done;"]
    
    
