apiVersion: v1
kind: Pod
metadata: 
  name: pod-ports
  namespace: dev
spec:
  containers:
    - image: nginx:1.17.1
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
      - containerPort: 80
        name: nginx-port
        protocol: TCP
