server:
  port: 10000
spring:
  application:
    name: k8s-demo-redis
  cloud:
    nacos:
      discovery:
        server-addr: nacos-headless.default.svc.cluster.local:8848
#        ip: k8s-demo-redis.default.svc.cluster.local
  redis:
    database: 0
    host: redis.default.svc.cluster.local
    port: 6379
    password: dream123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000

  rabbitmq:
    addresses: rabbitmq-cluster.default.svc.cluster.local
    port: 5672
    username: admin
    password: admin123
    listener:
      type: simple
      simple:
        default-requeue-rejected: false  #未消费则重新加入队列
        acknowledge-mode: manual
