server:
  port: 10000
spring:
  application:
    name: k8s-demo-redis

  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    Password: dream123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000
